---
pipeline:
  syntax_check:
    image: plugins/ansible:3
    settings:
      playbook: ansible-homelab.yml
      galaxy: requirements.yml
      inventory: tests/inventories/integration_testing/inventory
      syntax_check: true

  lint:
    image: python:3
    commands:
      - pip3 install ansible yamllint==1.27.1 ansible-lint==6.5
      - ansible-lint ansible-homelab.yml
      - yamllint .
