---
- hosts: all
  gather_facts: false
  vars_prompt:
    - name: api_key
      prompt: Enter the API key
  tasks:
    - name: Ensure API key is present in config file
      ansible.builtin.lineinfile:
        path: /etc/app/configuration.ini
        line: "API_KEY={{ api_key }}" 
        
- name: Start Portainer
  block:
    - name: Create Portainer Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ portainer_data_directory }}"

    - name: Portainer Docker Container
      community.docker.docker_container:
        name: "{{ portainer_container_name }}"
        image: "{{ portainer_image_name }}:{{ portainer_image_version }}"
        pull: true
        volumes:
          - "{{ portainer_data_directory }}:/data:rw"
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
          - "/etc/timezone:/etc/timezone:ro"
        ports:
          - "{{ portainer_port }}:9443"
        restart_policy: unless-stopped
        memory: "{{ portainer_memory }}"
  when: portainer_enabled is true

- name: Stop Portainer
  block:
    - name: Stop Portainer
      community.docker.docker_container:
        name: "{{ portainer_container_name }}"
        state: absent
  when: portainer_enabled is false